# Generated by Django 4.2.4 on 2023-11-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('google_scholar_id', models.IntegerField()),
                ('interest_list', models.CharField(max_length=1000)),
            ],
        ),
    ]
