# Generated by Django 4.2.4 on 2023-11-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0002_alter_mydata_google_scholar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydata',
            name='email',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='mydata',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='mydata',
            name='sub_title',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
