# Generated by Django 4.2.4 on 2023-11-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0005_alter_mydata_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydata',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
