# Generated by Django 4.2.4 on 2023-12-08 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0007_alter_mydata_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElsevierModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=200)),
                ('sub_title', models.CharField(blank=True, default='', max_length=1000)),
                ('url', models.URLField(blank=True, null=True)),
                ('orcid_id', models.CharField(blank=True, default='', max_length=100)),
                ('scopus_id', models.CharField(blank=True, default='', max_length=100)),
                ('eid', models.CharField(blank=True, default='', max_length=1000)),
                ('date_created', models.CharField(blank=True, default='', max_length=100)),
                ('affiliation_current', models.CharField(blank=True, default='', max_length=1000)),
                ('interests', models.CharField(blank=True, default='', max_length=1000)),
                ('affiliation_count', models.CharField(blank=True, default='', max_length=100)),
                ('coauthor_count', models.CharField(blank=True, default='', max_length=100)),
                ('h_index', models.CharField(blank=True, default='', max_length=100)),
                ('document_count', models.CharField(blank=True, default='', max_length=100)),
                ('citation_count', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='mydata',
            name='h_index',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mydata',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
