# Generated by Django 4.2.4 on 2023-12-08 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0009_alter_mydata_h_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elseviermodel',
            name='author_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
