# Generated by Django 4.2.4 on 2023-12-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0010_alter_elseviermodel_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydata',
            name='article_list',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='mydata',
            name='article_url_list',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='mydata',
            name='citations',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mydata',
            name='i10_index',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
